version: '3.8'

services:
  api:
    build:
      context: bnksystem/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - .env

  worker:
    build: 
      context: bnksystem/Dockerfile
    command: go run worker.go
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
